---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: sidecar
          image: benjaminhuo/opentelemetry-javaagent-all:v0.8.0 
          imagePullPolicy: IfNotPresent
          command: ["cp", "-r", "/opentelemetry/opentelemetry-javaagent-all.jar", "/sidecar/"]
          volumeMounts:
            - name: sidecar
              mountPath: /sidecar
      containers:
      - image: ${REPOSITORY_PREFIX}/api-gateway:latest
        name: api-gateway
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources: {}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: JAVA_OPTS
          value: -javaagent:/sidecar/opentelemetry-javaagent-all.jar
        - name: OTEL_OTLP_ENDPOINT
          value: otel-collector.demo.svc:55680
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=gateway
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: sidecar
              mountPath: /sidecar
      volumes:
        - name: sidecar  #共享agent文件夹
          emptyDir: {}
      restartPolicy: Always
status: {}
