FROM busybox:1.32
WORKDIR opentelemetry
RUN wget -O opentelemetry-javaagent-all.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v0.7.0/opentelemetry-javaagent-all.jar